Metrics optimization
dice-group/Lemming pull request #27
Opened 2021-10-31 21:58 UTC by wangzun66

This is a merge branch for all metrics' optimization!

2021-12-14 19:08 UTC, MichaelRoeder requested changes
Please have a look at my comments.

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/MetricUtils.java
> +    }
1. Javadoc is missing. It is unclear for the user why v1 and v2 are removed if you do not explicitly document it.
2. What about unit tests for this method?
3. Wouldn't the following be easier?
```java
    public static IntSet getVerticesInCommon(ColouredGraph graph, int v1, int v2) {
        IntSet v1Neighbors;
        v1Neighbors = graph.getInNeighbors(v1);
        v1Neighbors.addAll(graph.getOutNeighbors(v1));
        
        IntSet intersection = IntSetUtil.intersection(v1Neighbors, graph.getInNeighbors(v2));
        intersection.addAll(IntSetUtil.intersection(v1Neighbors, graph.getOutNeighbors(v2)));

        if (intersection.contains(v1))
            intersection.remove(v1);
        if (intersection.contains(v2))
            intersection.remove(v2);
        
        return intersection;
    }
```
It avoids the creation of the set that contains all neighbors of v2 since it is not needed to create it. It also removes `v1` and `v2` only from the result instead of removing it from intermediate results.

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/MaxVertexDegreeMetric.java
> +        } else { // Add an edge
I thought that this metric also stores the number of nodes that have the max vertex degree so that it only has to count again, if there is no other vertex that still has the maximum degree. What happened to this idea? :confused:

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/SingleValueMetricResult.java
> +    protected double result;
Javadoc comments are missing :wink:

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegree.java
> +        List<Double> list = new ArrayList<Double>();
A list of `Double` values? That is pretty expensive to return two simple numbers...

Why not `double result[] = new double[];`? It allows to return two values, uses less memory than an ArrayList and avoids the conversion of the double values into their `Double` objects.

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegree.java
> +        double flag = graphOperation == Operation.ADD ? 1 : -1;
`flag` is not a good name for this variable. Please rethink your choice :wink:

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +    private double numberOfVertices = 0.0; // Variable for storing number of vertices.
Nice comments. Why not as Javadoc so that a user can access them in an easier way? :wink:

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +     */
An interesting Javadoc comment. Unfortunately, it does not work as it should because it has to be put directly _in front_ of the class.

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +     * Returns the variance of in degrees computed after any edge operation
"... of in degrees ..." Why only in-degrees? (Applies also to other comments in this class)

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/edgetriangles/EdgeTriangleMetric.java
> +		newResult = newResult >= 0 ? newResult: 0;
Why this line is here? The new result should never be negative. Otherwise, something went wrong before. Hence, I would suggest to throw an exception or at least to log an error instead of fixing it quietly.

2021-12-14 19:08 UTC, MichaelRoeder commented on src/main/java/org/aksw/simba/lemming/metrics/single/nodetriangles/NodeTriangleMetric.java
> +		newResult = newResult>=0 ? newResult : 0;
The same as for the edge triangle metric.

2021-12-20 20:32 UTC, wangzun66 commented on src/main/java/org/aksw/simba/lemming/metrics/MetricUtils.java
> +    }
Done.

2021-12-20 20:33 UTC, wangzun66 commented on src/main/java/org/aksw/simba/lemming/metrics/single/edgetriangles/EdgeTriangleMetric.java
> +		newResult = newResult >= 0 ? newResult: 0;
Done.

2021-12-20 20:33 UTC, wangzun66 commented on src/main/java/org/aksw/simba/lemming/metrics/single/nodetriangles/NodeTriangleMetric.java
> +		newResult = newResult>=0 ? newResult : 0;
Done.

2021-12-21 08:51 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/SingleValueMetricResult.java
> +    protected double result;
Done

2021-12-21 08:51 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegree.java
> +        List<Double> list = new ArrayList<Double>();
Done

2021-12-21 08:51 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegree.java
> +        double flag = graphOperation == Operation.ADD ? 1 : -1;
Done

2021-12-21 08:51 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +    private double numberOfVertices = 0.0; // Variable for storing number of vertices.
Done

2021-12-21 08:51 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +     */
Done

2021-12-21 08:52 UTC, pra-kulk commented on src/main/java/org/aksw/simba/lemming/metrics/single/StdDevVertexDegreeMetricResult.java
> +     * Returns the variance of in degrees computed after any edge operation
Done

2021-12-23 09:48 UTC, atulpundir88 commented on src/main/java/org/aksw/simba/lemming/metrics/single/MaxVertexDegreeMetric.java
> +        } else { // Add an edge
Done. This logic is included now.

2022-08-23 12:20 UTC, merged